### ISSUE TITLE
Ascii decode error when loading atlasprint for a specific project

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-atlasprint#15]
It seems the content of the file `metadata.txt` triggers some parsing error when getting plugin metadata with configparser.

Quick workaround : replace `Michaël Douchin (3liz)` into `3liz` in the metadata file.

Error log

```
12:24:44 CRITICAL atlasprint[39333]: atlasprint - Error loading filter atlasprint : 'ascii' codec can't decode byte 0xc3 in position 459: ordinal not in$
12:24:44 WARNING Python error[39333]: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 590, in startServerPlugin
    server_plugins[packageName] = package.serverClassFactory(serverIface)
  File "/srv/qgis/plugins/atlasprint/__init__.py", line 31, in serverClassFactory
    return AtlasPrintServer(serverIface)
  File "/srv/qgis/plugins/atlasprint/atlasprintServer.py", line 40, in __init__
    serverIface.registerFilter(AtlasPrintFilter(serverIface), 50)
  File "/srv/qgis/plugins/atlasprint/filters/atlasprintFilter.py", line 56, in __init__
    self.getMetadata()
  File "/srv/qgis/plugins/atlasprint/filters/atlasprintFilter.py", line 67, in getMetadata
    config.read(mfile)
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1012, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 459: ordinal not in range(128)

12:24:44 WARNING Couldn't load server plugin atlasprint due to an error when calling its serverClassFactory() method[39333]: Couldn't load server plugin$


```

**Comment by mdouchin** [comment]
We should also add a `raise` after catching the exception in `atlasprintServer.py` to get the full trace.
